export const planetConstants = {
  GET_PLANET_REQUEST_OUT: "GET_PLANET_REQUEST_OUT",
  GET_PLANET_FAIL: "GET_PLANET_FAIL",
  GET_PLANET_SUCCESS: "GET_PLANET_SUCCESS",
  SET_PLANET_LIST: "SET_PLANET_LIST",
  SET_BARCHART_DATA: "SET_BARCHART_DATA",
  SET_PAGINATION: "SET_PAGINATION",
};
